[[services]]
name = "backend"
root = "./server"
build = "npm install"
start = "npm start"

[[services]]
name = "frontend"
root = "./client/smartmad"
build = "npm install && npm run build"
start = "npx serve -s build"