services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smartrecipe
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
      - "3307:3306"
    volumes:
      - ./Server/database:/docker-entrypoint-initdb.d  # Populate MySQL with initial scripts
      - mysql_data:/var/lib/mysql
    networks:
      - app_network


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  mysql_data:
  mongodb_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:

networks:
  app_network:
    driver: bridge


  