version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smartrecipe
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./Server/database:/docker-entrypoint-initdb.d  # Populate MySQL with initial scripts
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  mongodb:
    build:
      context: ./mongoDB
      dockerfile: Dockerfile-mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

volumes:
  mysql_data:
  mongodb_data:

networks:
  app_network:
    driver: bridge


  