name: CI/CD with Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli -h 127.0.0.1 -p 6379 ping | grep PONG" --health-interval 5s --health-timeout 3s --health-retries 10
    steps:
      - uses: actions/checkout@v4

      # Step 1: Ensure server directory exists
      - name: Ensure Server Directory
        run: |
          if [ ! -d "./server" ]; then
            echo "Error: ./server directory does not exist"
            exit 1
          fi

      # Step 2: Install backend dependencies
      - name: Install Dependencies (Backend)
        run: |
          npm install
          npm install cypress --save-dev
        working-directory: ./server

      # Step 3: Wait for Redis to be ready
      - name: Wait for Redis to Start
        run: |
          npx wait-on tcp:localhost:6379

      # Step 4: Start backend server in the background
      - name: Start Backend Server
        run: |
          nohup npm run start > backend.log 2>&1 &
        working-directory: ./server

      # Step 5: Check if Backend Log Exists
      - name: Check for Backend Log
        run: |
          if [ ! -f "./server/backend.log" ]; then
            echo "Error: Backend log not created"
            exit 1
          fi

      # Step 6: Output Backend Logs
      - name: Output Backend Logs
        run: |
          cat ./server/backend.log

      # Step 7: Wait for the backend server to be ready
      - name: Wait for Backend Server to Start
        run: |
          npx wait-on http://localhost:8080

      # Step 8: Run Cypress tests
      - name: Run Cypress Tests
        run: |
          npx cypress run --headless --browser chrome --spec './server/tests/cypress/cypress/e2e/spec.cy.js'
        working-directory: .cypress
