name: CI/CD with Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli -h 127.0.0.1 -p 6379 ping | grep PONG" --health-interval 5s --health-timeout 3s --health-retries 10
    steps:
      - uses: actions/checkout@v4

      # Step 1: Install backend dependencies
      - name: Install Dependencies (Backend)
        run: |
          npm install
          npm install cypress --save-dev
        working-directory: ./server

      # Step 2: Install and Start Frontend
      - name: Install and Start Frontend
        run: |
          npm install
          npm run start & 
        working-directory: ./client/smartmad

      # Step 3: Start Docker Compose for services (if any)
      - name: Start Docker Compose
        run: |
          npm run docker
        working-directory: ./server

      # Step 4: Wait for Redis to be ready
      - name: Wait for Redis to Start
        run: |
          npx wait-on tcp:localhost:6379

      # Step 5: Start backend server in the background
      - name: Start Backend Server
        run: |
          nohup npm run start & 
        working-directory: ./server

      - name: Wait for Backend and Frontend
        run: |
          npx wait-on tcp:localhost:8080
          npx wait-on tcp:localhost:3000

      # Step 6: Run Cypress tests
      - name: Run Cypress Tests
        run: |
          npx cypress run --browser chrome --spec './cypress/e2e/spec.cy.js'
        working-directory: ./server/tests/cypress

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Client-side build steps
      - name: Install Dependencies (Client)
        run: npm install
        working-directory: ./client/smartmad
      - name: Build Application (Client)
        run: npm run build
        working-directory: ./client/smartmad

      # Server-side test steps
      - name: Install Dependencies (Server)
        run: npm install
        working-directory: ./server

      # Start Docker Compose for server if needed
      - name: Start Docker Compose for Server
        run: |
          npm run docker
        working-directory: ./server

      # Optional: List files (for debugging)
      - name: List Files
        run: ls -R
        working-directory: ./client/smartmad
